---
title: "Tutorial_8"
format: html
editor: visual
---

```{r}
library(readr)
library(ggplot2)
library(tidyverse)
```


```{r}
Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019 <- read_csv("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019.csv")
View(Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019)
```

```{r}
barchart <- ggplot(Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019, aes(x = Year, y =`Incidents Recorded`)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(x = "Offence Division", y = "Incidents", title = "Offence Division vs Incidents") +
  theme_minimal() 
barchart
```


```{r}
Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019 %>%
  group_by(Year) %>%
  summarise(count = sum(as.integer(`Incidents Recorded`), na.rm = TRUE)) %>%
  ggplot() +
  geom_col(aes(x = Year, y = count), position = "dodge") +
  ggtitle(" Year wise Incidents counts ") +
  scale_fill_brewer(palette = "Dark2") + 
  theme_bw(base_size = 12)
```




